name: dowhy
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib=3.4
  - numpy
  - pip
  - pandas
  - python=3.10
  - seaborn
  - scikit-learn
  - pip:
    - dowhy
    - shap==0.41
    - xgboost==1.5
